version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install ./mpc-client
    - pip install pandas "mkdocs>=1.5,<2" mkdocs-material "mkdocstrings[python]" "mkdocs-jupyter>=0.24" "nbconvert>=7.0,<8"
    - cd mpc-client && mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
