version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - cd mpc-client && pip install -e ".[all,docs]"
    - cd mpc-client && mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
