"""This file constructs a KernelSpecifier object for each of the station-codes/obs-codes of artificial satellites for which `wis.py` knows how to get spice-kernels.

************************************************************
NB: The original intent of the KernelSpecifier object was to
    specify *all* of the kernels necessary to calculate
    positions for a given obs-code.  However, for satellites,
    we only need to specify the additional kernels that are
    NOT already covered by the ground-based kernels.

    Moreover, trying to explicitly specify *all* kernels has
    lead to conflicts in the past.

    => Any unit-/integration-tests that use the kernels
    likely need to load ALL kernels
************************************************************

The file-selections for Kepler were scraped-together by MJP in 2019, and may likely out-of-date.
(edit 05-2026: the TESS mission is still adding fresh kernels to that same page, so
all good for TESS at least)

There are many mission kernels available at: https://naif.jpl.nasa.gov/pub/naif/
 - TODO: see if any of them are of use for MPC obs-codes
"""

# Local imports
# -----------------------------------------
from wis.kernelspecifier import KernelSpecifier

TESS = KernelSpecifier(
    obscodeMPC="C57",
    obscodeJPL="-95",
    name="TESS",
    files=[],
    wildcards={"https://archive.stsci.edu/missions/tess/models/": "TESS_EPH_DEF*"},
)

KEPLER = KernelSpecifier(
    obscodeMPC="C55",
    obscodeJPL="-227",
    name="Kepler/K2",
    files=[
        "https://archive.stsci.edu/pub/k2/spice/kplr2018134232543.tsc",
        "https://archive.stsci.edu/pub/k2/spice/spk_2018290000000_2018306220633_kplr.bsp",
    ],
    wildcards={},
)

GAIA = KernelSpecifier(
    obscodeMPC="258",
    obscodeJPL="-123",
    name="Gaia",
    # gaia_flp_20131219_21250328_v01.bsp (ESA SPICE kernel dataset v1.1.0, July 2025):
    #   Per aareadme.txt: "SPICE SPK file that contains Gaia reconstructed orbit
    #   information from launch 2013-12-19 to the end of mission 2025-03-28 and the
    #   predicted orbit information of the spacecraft position after this date till
    #   April 2125. The file is generated by the ESA SPICE Service using data from
    #   the Flight Dynamics team."
    files=[
        "https://spiftp.esac.esa.int/data/SPICE/GAIA/kernels/spk/gaia_flp_20131219_21250328_v01.bsp",
    ],
    wildcards={},
)

HST = KernelSpecifier(
    obscodeMPC="250",
    obscodeJPL="-48",
    name="HST",
    files=[
        "https://naif.jpl.nasa.gov/pub/naif/HST/kernels/spk/hst.bsp",
    ],
    wildcards={},
    timecritical=[
        "https://naif.jpl.nasa.gov/pub/naif/HST/kernels/spk/hst.bsp",
    ],
)

JWST = KernelSpecifier(
    obscodeMPC="274",
    obscodeJPL="-170",
    name="JWST",
    # there are two kernels here: the predicted and reconstructed trajectories.
    # we should load the predicted first and reconstructed second, since SPICE gives
    # later-loaded kernels priority when their coverage overlaps. this way if someone
    # asks for a position in the past, they get the reconstructed position, and only use
    # the predicted position for future times where the reconstructed kernel has nothing
    files=[
        "https://naif.jpl.nasa.gov/pub/naif/JWST/kernels/spk/jwst_pred.bsp",
        "https://naif.jpl.nasa.gov/pub/naif/JWST/kernels/spk/jwst_rec.bsp",
    ],
    wildcards={},
    timecritical=[
        "https://naif.jpl.nasa.gov/pub/naif/JWST/kernels/spk/jwst_pred.bsp",
        "https://naif.jpl.nasa.gov/pub/naif/JWST/kernels/spk/jwst_rec.bsp",
    ],
)

# Keep satellite_kernels dict for backward compatibility in internal code
satellite_kernels = {
    "C57": TESS,
    "C55": KEPLER,
    "258": GAIA,
    "250": HST,
    "274": JWST,
}

__all__ = [
    "GAIA",
    "HST",
    "JWST",
    "KEPLER",
    "TESS",
    "satellite_kernels",
]
