name: Build and public mpc-orb to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    environment: mpc-public
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_PASSWORD }}
